### PR TITLE
Update readability.js

### PR DESCRIPTION
**Pull request by masihyeganeh**
Return document tree of jsdom as well, so user won't need to load another jsdom instance if he need to get another data from page

### CODE REVIEW

**Comment by hellocodeM** [comment]
Thank you.

**Comment by masihyeganeh** [comment]
Thanks. would you please update it's version, so I can see this change in npm too?

**Comment by hellocodeM** [comment]
I have updated the version to 0.1.3, thank you for you contribution.

**Comment by hellocodeM** [comment]
Actually, this program is still worthy of improvement, where it could not throw an exception when fail to extract the main content. I'm right busy recently, if you someone could help, that's was really good.

**Comment by masihyeganeh** [comment]
I don't know what's wrong bug [npm](https://www.npmjs.com/package/easy-readability) is not updated yet

**Pull request merged**
